"use client";

import React from "react";
import Link from "next/link";
import {
  ArrowLeft,
  ShieldAlert,
  Brain,
  Leaf,
  Calendar,
  MapPin,
  TrendingDown,
  TrendingUp,
  DollarSign,
  CloudRain,
  Thermometer,
  Layers,
  History,
  FileCheck2,
  Cpu,
  Sparkles,
  Info,
} from "lucide-react";
import { PredictionRecordDTO } from "../types";

interface PredictionDetailProps {
  prediction: PredictionRecordDTO & {
    auditLogs?: Array<{
      id: string;
      action: string;
      details?: string | null;
      timestamp?: string | Date;
      createdAt?: string | Date;
      user?: {
        name?: string | null;
        fullName?: string | null;
        email: string | null;
        role: string;
      } | null;
    }>;
  };
  userRole: "OMAG_HEAD" | "OMAG_STAFF";
}

export const PredictionDetail: React.FC<PredictionDetailProps> = ({
  prediction,
  userRole,
}) => {
  const backPath = userRole === "OMAG_HEAD" ? "/head/predictions" : "/staff/predictions";
  const farmer = prediction.crop?.parcel?.farm?.farmer;
  const farm = prediction.crop?.parcel?.farm;
  const parcel = prediction.crop?.parcel;
  const crop = prediction.crop;
  const model = prediction.model;
  const snapshot = prediction.inputFeaturesSnapshot || {};

  const reductionPct = prediction.predictedYieldReductionPercent || 0;
  const normalTons = prediction.projectedNormalYieldTons || 0;
  const remainingTons = prediction.predictedRemainingYieldTons || 0;
  const reductionTons = Math.max(0, normalTons - remainingTons);
  const areaHa = crop?.plantedAreaHa || snapshot.plantedAreaHa || 1;

  const normalTonsHa = areaHa > 0 ? normalTons / areaHa : 0;
  const remainingTonsHa = areaHa > 0 ? remainingTons / areaHa : 0;

  return (
    <div className="space-y-6 max-w-6xl mx-auto pb-12">
      {/* 1. Header & Navigation */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <Link
            href={backPath}
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-emerald-700 transition-colors mb-2"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back to Yield & Loss Predictions</span>
          </Link>
          <h1 className="text-2xl font-black text-slate-900 tracking-tight flex items-center gap-3">
            <span>Prediction Dossier</span>
            <span className="text-xs font-mono font-normal px-2.5 py-1 rounded-md bg-emerald-100 text-emerald-800 border border-emerald-200">
              ID: {prediction.id.slice(0, 8)}...
            </span>
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Generated on {new Date(prediction.predictionTimestamp).toLocaleString()}
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <span className="px-3 py-1 rounded-lg bg-amber-100/80 border border-amber-300 text-amber-900 text-xs font-bold flex items-center gap-1.5">
            <span>🟡 PROPOSED SYSTEM DESIGN</span>
          </span>
          <span className="px-3 py-1 rounded-lg bg-emerald-100/80 border border-emerald-300 text-emerald-900 text-xs font-bold flex items-center gap-1.5">
            <Cpu className="h-3.5 w-3.5 text-emerald-700" />
            <span>{model?.algorithm || "RandomForestRegressor"}</span>
          </span>
        </div>
      </div>

      {/* 2. PCIC Boundary & Statutory Non-Approval Notice */}
      <div className="rounded-2xl border border-amber-300/80 bg-amber-50 p-4 shadow-2xs">
        <div className="flex items-start gap-3.5">
          <ShieldAlert className="h-6 w-6 text-amber-600 shrink-0 mt-0.5" />
          <div className="text-xs text-amber-950 space-y-1">
            <p className="font-bold text-sm text-amber-950">
              Official PCIC Boundary & Advisory Disclaimer
            </p>
            <p className="leading-relaxed text-amber-900">
              This yield reduction and economic loss dossier is an <strong>analytical estimate</strong> generated by the OMAG Polomolok Machine Learning module for localized municipal risk assessment and planning. This document <strong>DOES NOT</strong> constitute official Philippine Crop Insurance Corporation (PCIC) claim approval, formal adjusters’ assessment, or guarantee of indemnity payout.
            </p>
          </div>
        </div>
      </div>

      {/* 3. Core Prediction Metrics Display */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Normal Yield */}
        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xs">
          <div className="flex items-center justify-between text-slate-500">
            <span className="text-xs font-bold uppercase tracking-wider">Projected Normal Yield</span>
            <TrendingUp className="h-5 w-5 text-emerald-600" />
          </div>
          <div className="mt-3">
            <span className="text-2xl font-black text-slate-900 font-mono">
              {normalTons.toFixed(2)}
            </span>{" "}
            <span className="text-xs font-semibold text-slate-500">total tons</span>
          </div>
          <p className="text-xs text-slate-500 mt-1 font-mono">
            {normalTonsHa.toFixed(2)} tons / ha baseline
          </p>
        </div>

        {/* Remaining Harvest */}
        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xs">
          <div className="flex items-center justify-between text-slate-500">
            <span className="text-xs font-bold uppercase tracking-wider">Predicted Remaining</span>
            <Leaf className="h-5 w-5 text-teal-600" />
          </div>
          <div className="mt-3">
            <span className="text-2xl font-black text-teal-900 font-mono">
              {remainingTons.toFixed(2)}
            </span>{" "}
            <span className="text-xs font-semibold text-slate-500">total tons</span>
          </div>
          <p className="text-xs text-slate-500 mt-1 font-mono">
            {remainingTonsHa.toFixed(2)} tons / ha estimated
          </p>
        </div>

        {/* Yield Reduction */}
        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xs">
          <div className="flex items-center justify-between text-slate-500">
            <span className="text-xs font-bold uppercase tracking-wider">Yield Reduction</span>
            <TrendingDown className="h-5 w-5 text-amber-600" />
          </div>
          <div className="mt-3">
            <span className="text-2xl font-black text-amber-700 font-mono">
              {reductionPct > 0 ? `-${reductionPct.toFixed(1)}%` : "0.0%"}
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-1 font-mono">
            -{reductionTons.toFixed(2)} tons difference
          </p>
        </div>

        {/* Economic Crop Loss */}
        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xs">
          <div className="flex items-center justify-between text-slate-500">
            <span className="text-xs font-bold uppercase tracking-wider">Est. Economic Loss</span>
            <DollarSign className="h-5 w-5 text-red-600" />
          </div>
          <div className="mt-3">
            {prediction.estimatedEconomicLossPhp !== null ? (
              <span className="text-2xl font-black text-red-700 font-mono">
                ₱{prediction.estimatedEconomicLossPhp.toLocaleString("en-US", { maximumFractionDigits: 2 })}
              </span>
            ) : (
              <span className="text-sm font-semibold text-slate-400 italic">
                Price Data Unavailable
              </span>
            )}
          </div>
          <p className="text-xs text-slate-500 mt-1">
            {snapshot.unitPricePhpKg
              ? `@ ₱${snapshot.unitPricePhpKg}/kg unit price`
              : "No official commodity price set"}
          </p>
        </div>
      </div>

      {/* 4. Two-Column Detailed Breakdown */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left Column: Beneficiary & Crop Details */}
        <div className="space-y-6">
          {/* Beneficiary Card */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xs space-y-4">
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-3">
              <MapPin className="h-4 w-4 text-emerald-600" />
              Beneficiary & Parcel Profile
            </h3>

            <div className="grid grid-cols-2 gap-4 text-xs">
              <div>
                <span className="text-slate-500 block">Farmer Name</span>
                <span className="font-bold text-slate-900 text-sm">
                  {farmer ? `${farmer.firstName} ${farmer.lastName}` : "Unknown"}
                </span>
              </div>

              <div>
                <span className="text-slate-500 block">RSBSA System ID</span>
                <span className="font-mono font-bold text-slate-800">
                  {farmer?.rsbsaNumber || "Not Assigned"}
                </span>
              </div>

              <div>
                <span className="text-slate-500 block">Barangay Jurisdiction</span>
                <span className="font-semibold text-slate-800">
                  {farm?.barangay || "Polomolok"}
                </span>
              </div>

              <div>
                <span className="text-slate-500 block">Parcel Reference</span>
                <span className="font-mono font-semibold text-slate-800">
                  {parcel?.parcelNumber || "N/A"}
                </span>
              </div>
            </div>
          </div>

          {/* Crop Planting & Agronomic Profile */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xs space-y-4">
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-3">
              <Leaf className="h-4 w-4 text-emerald-600" />
              Crop & Agronomic Details
            </h3>

            <div className="grid grid-cols-2 gap-4 text-xs">
              <div>
                <span className="text-slate-500 block">Crop Type</span>
                <span className="font-bold text-slate-900">
                  {crop?.cropType || snapshot.cropType || "Unknown"}
                </span>
              </div>

              <div>
                <span className="text-slate-500 block">Variety</span>
                <span className="font-semibold text-slate-800">
                  {crop?.variety || "Standard Hybrid"}
                </span>
              </div>

              <div>
                <span className="text-slate-500 block">Season / Year</span>
                <span className="font-semibold text-slate-800">
                  {crop?.season || "Wet"} {crop?.year || 2026}
                </span>
              </div>

              <div>
                <span className="text-slate-500 block">Planted Area</span>
                <span className="font-mono font-bold text-slate-800">
                  {areaHa.toFixed(2)} hectares
                </span>
              </div>
            </div>
          </div>

          {/* Damage & Environmental Stressors */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xs space-y-4">
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-3">
              <CloudRain className="h-4 w-4 text-blue-600" />
              Environmental Stressors & Damage Inputs
            </h3>

            <div className="grid grid-cols-2 gap-4 text-xs">
              <div>
                <span className="text-slate-500 block">Reported Damage %</span>
                <span className="font-bold font-mono text-amber-800">
                  {snapshot.damagePercentage !== undefined ? `${snapshot.damagePercentage}%` : "None"}
                </span>
              </div>

              <div>
                <span className="text-slate-500 block">Damage Cause</span>
                <span className="font-semibold text-slate-800 capitalize">
                  {snapshot.damageCause ? snapshot.damageCause.replace("_", " ") : "None reported"}
                </span>
              </div>

              <div>
                <span className="text-slate-500 block">Rainfall</span>
                <span className="font-mono text-slate-800">
                  {snapshot.rainfallMm !== undefined ? `${snapshot.rainfallMm} mm` : "Normal"}
                </span>
              </div>

              <div>
                <span className="text-slate-500 block">Average Temperature</span>
                <span className="font-mono text-slate-800">
                  {snapshot.temperatureC !== undefined ? `${snapshot.temperatureC} °C` : "28.0 °C"}
                </span>
              </div>

              <div>
                <span className="text-slate-500 block">Soil Type</span>
                <span className="font-semibold text-slate-800">
                  {snapshot.soilType || "Clay Loam"}
                </span>
              </div>

              <div>
                <span className="text-slate-500 block">Fertilizer Application</span>
                <span className="font-mono text-slate-800">
                  {snapshot.fertilizerKgHa !== undefined ? `${snapshot.fertilizerKgHa} kg/ha` : "120 kg/ha"}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Model Registry Snapshot & Audit Trail */}
        <div className="space-y-6">
          {/* ML Model Performance & Registry */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xs space-y-4">
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-3">
              <Brain className="h-4 w-4 text-purple-600" />
              Model Registry & Evaluation Metrics
            </h3>

            <div className="space-y-3 text-xs">
              <div className="flex justify-between items-center py-1 border-b border-slate-100">
                <span className="text-slate-500">Model Name & Algorithm</span>
                <span className="font-semibold text-slate-800">
                  {model?.modelName || "RandomForest Crop Yield Model"}
                </span>
              </div>

              <div className="flex justify-between items-center py-1 border-b border-slate-100">
                <span className="text-slate-500">Model Version</span>
                <span className="font-mono font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                  {model?.modelVersion || "v1.0.0"}
                </span>
              </div>

              <div className="grid grid-cols-3 gap-2 pt-2 text-center">
                <div className="bg-slate-50 border border-slate-200/80 rounded-xl p-2.5">
                  <span className="text-[10px] uppercase font-bold text-slate-500 block">R² Score</span>
                  <span className="font-mono font-bold text-slate-900 text-sm">
                    {model?.r2Score !== undefined ? model.r2Score.toFixed(4) : "—"}
                  </span>
                </div>

                <div className="bg-slate-50 border border-slate-200/80 rounded-xl p-2.5">
                  <span className="text-[10px] uppercase font-bold text-slate-500 block">MAE (t/ha)</span>
                  <span className="font-mono font-bold text-slate-900 text-sm">
                    {model?.mae !== undefined ? model.mae.toFixed(3) : "—"}
                  </span>
                </div>

                <div className="bg-slate-50 border border-slate-200/80 rounded-xl p-2.5">
                  <span className="text-[10px] uppercase font-bold text-slate-500 block">RMSE (t/ha)</span>
                  <span className="font-mono font-bold text-slate-900 text-sm">
                    {model?.rmse !== undefined ? model.rmse.toFixed(3) : "—"}
                  </span>
                </div>
              </div>

              <p className="text-[11px] text-slate-500 italic mt-2">
                * Metrics evaluated on distinct 20% test partition of stratified Polomolok agricultural dataset.
              </p>
            </div>
          </div>

          {/* Audit Trail History */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xs space-y-4">
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-3">
              <History className="h-4 w-4 text-slate-600" />
              Municipal Audit History
            </h3>

            {prediction.auditLogs && prediction.auditLogs.length > 0 ? (
              <div className="space-y-3">
                {prediction.auditLogs.map((log) => (
                  <div key={log.id} className="p-3 bg-slate-50 border border-slate-200/70 rounded-xl text-xs space-y-1">
                    <div className="flex justify-between items-center">
                      <span className="font-bold text-slate-800">{log.action}</span>
                      <span className="text-[10px] text-slate-400">
                        {new Date(log.timestamp || log.createdAt || Date.now()).toLocaleString()}
                      </span>
                    </div>
                    <p className="text-slate-600">{log.details || "Prediction generated and recorded."}</p>
                    <div className="text-[11px] text-emerald-700 font-medium">
                      By: {log.user?.fullName || log.user?.name || log.user?.email || "OMAG Staff"} ({log.user?.role || "OMAG_STAFF"})
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="p-4 bg-slate-50 rounded-xl text-xs text-slate-500 text-center">
                Prediction logged with immutable timestamp on {new Date(prediction.predictionTimestamp).toLocaleDateString()}.
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
